>>> Square = __import__('4-square').Square


Instantiation Tests
--------------------------------------------
""" Regular test """
>>> my_square = Square(89)
>>> my_square.area()
7921
>>> my_square.size
89

""" Multiple Arg Test """
>>> my_square = Square(1, 2)
Traceback (most recent call last):
	...
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

""" Negative Test """
>>> my_square = Square(-2)
Traceback (most recent call last):
	...
ValueError: size must be >= 0

""" None Test """
>>> my_square = Square(None)
Traceback (most recent call last):
	...
TypeError: size must be an integer

""" String Test """
>>> my_square = Square("yo")
Traceback (most recent call last):
	...
TypeError: size must be an integer

""" Float Test """
>>> my_square = Square(3.2)
Traceback (most recent call last):
	...
TypeError: size must be an integer

""" List Test """
>>> my_square = Square([46, 87, 98])
Traceback (most recent call last):
	...
TypeError: size must be an integer

""" Empty Test """
>>> my_square = Square()
>>> my_square.area()
0
>>> my_square.size
0

""" Tuple Test """
>>> my_square = Square(1,)
>>> my_square.size
1

""" Boolean Test """
>>> my_square = Square(True)
>>> my_square.area()
1

Setter Tests
-----------------------------------------------------------
>>> my_square = (2, 3)
>>> my_square.size = {'key' : 'value'}
Traceback (most recent call last):
	...
AttributeError: 'tuple' object has no attribute 'size'

>>> my_square.size = (2, 3)
Traceback (most recent call last):
	...
AttributeError: 'tuple' object has no attribute 'size'

>>> my_square.size = [2, 3]
Traceback (most recent call last):
	...
AttributeError: 'tuple' object has no attribute 'size'

>>> my_square.size = "hey"
Traceback (most recent call last):
	...
AttributeError: 'tuple' object has no attribute 'size'

>>> my_square.size = {'3', '2', '1'}
Traceback (most recent call last):
	...
AttributeError: 'tuple' object has no attribute 'size'

>>> my_square.size = True
Traceback (most recent call last):
	...
AttributeError: 'tuple' object has no attribute 'size'
